# Generated by Django 3.1.2 on 2020-10-21 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
